[lb]
load_balancer ansible_host=172.31.94.81 ansible_ssh_user='ubuntu'

[uat_webservers]
Web1 ansible_host=172.31.84.177 ansible_ssh_user='ec2-user'
Web2 ansible_host=172.31.81.75 ansible_ssh_user='ec2-user'

[db]
db ansible_host=172.31.86.101 ansible_ssh_user='ubuntu'
